### ISSUE TITLE
Stop certReloader.GetCertificateFunc() to create new certificate

### ISSUE THREAD

**Issue by yaseenyahya** [foomo/simplecert#18]
Stop certReloader.GetCertificateFunc() to create new certificate .I have uploaded my godaddy certificate to cacheDir but its always overwrite.

**Comment by dreadl0ck** [comment]
The certReloader should only create a new certificate if your cert will expire in less hours than specified in config.RenewBefore (simplecert.Default has this value set to 30 days).

Please provide your configuration and simplecert.log output for further assistance (don't forget to remove private information).

In general, I don't see much sense in using this library if you are not using it to manage letsencrypt certificates, and it has not been tested for that usecase.

If you have a valid certificate already, why don't you supply it to the standard library http.ListenAndServeTLS function directly?

**Comment by yaseenyahya** [comment]
while using simple cert i am having invalid ssl certificate. issuing certificate on my computer address not on my domain.
![simplecert](https://user-images.githubusercontent.com/14994811/105703049-7c17c900-5f2e-11eb-9346-16cf2ebaf1b8.png)

**Comment by yaseenyahya** [comment]
here is my code 
cfg := simplecert.Default
	cfg.Domains = []string{"upload.domain.com", "www.upload.domain.com"}
	cfg.CacheDir = "letsencrypt"

	cfg.Local = true
	 certReloader, err := simplecert.Init(cfg, func() {
		os.Exit(0)
	})
	if err != nil {
createText(fmt.Sprintf("simplecert init failed: %s", err), 0)
		
	}

	createText(fmt.Sprintf("starting HTTP Listener on Port%s", ":8080"), 0)
	
	go http.ListenAndServe(":8080", http.HandlerFunc(simplecert.Redirect))

	// init strict tlsConfig with certReloader
	tlsconf := tlsconfig.NewServerTLSConfig(tlsconfig.TLSModeServerStrict)

	// now set GetCertificate to the reloaders GetCertificateFunc to enable hot reload
	tlsconf.GetCertificate = certReloader.GetCertificateFunc()

	// init server
	server.Addr = ":8086";
		server.TLSConfig = tlsconf;
		server.Handler =   nil;
	
createText(fmt.Sprintf("now visit: https://%s", cfg.Domains[0]), 0)
	

	// lets go
	server.ListenAndServeTLS("", "");

**Comment by dreadl0ck** [comment]
Since you are using simplecert in local mode:

- Did you install mkcert (https://github.com/FiloSottile/mkcert) on your system?
- What OS are you running on?
- Please ensure that one of the supported root stores is present: https://github.com/FiloSottile/mkcert#supported-root-stores
- Please attach the output of your simplecert.log

It looks like a certificate for local use was generated but your system root store does not trust it.

**Comment by yaseenyahya** [comment]
1. yes installed mkcert on my server..
2. Microsoft Window Server 2016
3. How am i going to find my root stores capability?
4. 2021/01/25 16:53:54 [INFO] simplecert: checking if cacheDir letsencrypt\local exists...
2021/01/25 16:53:54 [INFO] simplecert: cacheDir does not exist - creating it
2021/01/25 16:53:54 [INFO] no cached cert found. Creating a new one for local development...
2021/01/25 16:53:54 [INFO] please note that for this cert to be trusted by firefox or nodejs additional steps are necessary!
2021/01/25 16:53:54 [INFO] see instructions at https://github.com/FiloSottile/mkcert
2021/01/25 16:53:54 [INFO] renaming upload.a**********k..com+1.pem to letsencrypt\local\cert.pem
2021/01/25 16:53:54 [INFO] renaming upload.a**********k.com+1-key.pem to letsencrypt\local\key.pem
2021/01/25 16:54:05 http: TLS handshake error from 59.103.124.223:14852: remote error: tls: unknown certificate
2021/01/25 16:54:05 http: TLS handshake error from 59.103.124.223:14853: remote error: tls: unknown certificate
2021/01/25 17:14:28 http: TLS handshake error from 59.103.124.223:12605: remote error: tls: unknown certificate
2021/01/25 17:14:28 http: TLS handshake error from 59.103.124.223:12603: remote error: tls: unknown certificate

**Comment by dreadl0ck** [comment]
Could it be that you are connecting from your local computer to the Server?
In that case the certificate will be rejected because the browser on your local computer does not trust it.

Local mode is meant to be used for connecting from the same system where the service is running,
so you can test running the service with a working TLS connection on your development machine.

If you have a Server and a DNS name that resolves to it, you must use the production mode.
You can find an example here: https://github.com/foomo/simplecert/blob/master/examples/production/main.go
It will fetch a letsencrypt certificate (local mode generates a self-signed one!), which will be trusted by your browser.

**Comment by yaseenyahya** [comment]
Problem was resolved after using production code. Thankyou
